### ISSUE TITLE
Incrementally generate maze

### ISSUE THREAD

**Issue by inoryy** [marekpagel/Music-Maze#2]
When our camera gets near next connector, draw a new set of corridors and next connectors.
I've got a single step working here https://github.com/marekpagel/Music-Maze/blob/master/index.html#L82-L96 (you can manually move with arrow keys)
Figure out how to generalize this to keep it going infinitely. Make sure to remove existing corridors after 1-2 turns, otherwise you'll run into collision issues.

**Comment by karulont** [comment]
Probably we should draw more sections ahead.
However then we need some logic to avoid overlapping sections.

**Comment by inoryy** [comment]
@marekpagel any progress?

**Comment by marekpagel** [comment]
Generating another level ahead, should be enough for now.
