### ISSUE TITLE
Fix automated camera movement

### ISSUE THREAD

**Issue by inoryy** [marekpagel/Music-Maze#3]
After #2 is done, fix the camera to move to next connector automatically.
I've had a semi-working demo here https://github.com/marekpagel/Music-Maze/tree/demo
There seems to be a small bug with rotation right now, fix that.

Then figure out how to keep going infinitely. I've added the fundamental API for that here https://github.com/marekpagel/Music-Maze/blob/master/src/camera.js, figure out how to keep the queue going. Keep in mind that we're dealing with Javascript, so you most likely need to deal with callbacks like it's currently done in camera `_move` and `_rotate` methods.

**Comment by karulont** [comment]
This is done.
