### ISSUE TITLE
Feed music analysis as probability distribution to maze.next

### ISSUE THREAD

**Issue by inoryy** [marekpagel/Music-Maze#5]
[maze.next()](https://github.com/marekpagel/Music-Maze/blob/master/src/maze.js#L37-L42) takes probability distribution for the 3 connectors. Currently they're set as `Math.random()`. Figure out a way to generate these from music.

Also make sure that at least one connector is always present. Currently this is _sometimes_ not the case.

**Comment by karulont** [comment]
This is kind of done. Probabilities can be fine tuned later.
